'use client';

import { useState } from 'react';
import type { DecisionTree, EngineState, TreeNode } from '@/lib/engines/types';
import { CatTag, SecLabel } from './shared';

interface Props {
  moduleId: string;
  moduleTitle: string;
  tree: DecisionTree;
  state: EngineState;
  onRestart: () => void;
  onHub: () => void;
}

interface Decision { q: string; a: string; sub?: string; multi?: boolean }
interface RecBlock { title: string; tagline?: string; pts: string[]; tools: string[] }

function shorten(label: string, max = 16): string {
  const s = label.replace(/[—–].*$/, '').trim();
  return s.length > max ? s.slice(0, max - 1) + '…' : s;
}

function downloadText(filename: string, text: string) {
  const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Final "reward" screen for every Decision Engine module. Reconstructs the
 * path the student took (from engine state + the tree) into a referable,
 * printable, downloadable workflow — instead of bouncing back to the hub.
 */
export function WorkflowSummary({ moduleId, moduleTitle, tree, state, onRestart, onHub }: Props) {
  const [downloaded, setDownloaded] = useState(false);

  // state.hist holds the ordered node ids visited, including the terminal node.
  const path = state.hist;

  const decisions: Decision[] = [];
  const recBlocks: RecBlock[] = [];
  const chips: { k: string; v: string }[] = [];
  const toolSet = new Set<string>();

  for (const id of path) {
    const n = tree[id] as TreeNode | undefined;
    if (!n) continue;

    if ('tools' in n && n.tools) n.tools.forEach((t) => toolSet.add(t));

    if (n.type === 'q') {
      const a = state.ans[id];
      if (a?.label) {
        decisions.push({ q: n.q || n.title, a: a.label, sub: a.sub });
        if (chips.length < 6) chips.push({ k: shorten(n.cat || n.title), v: a.badge || a.label.replace(/[—–].*$/, '').trim() });
      }
    } else if (n.type === 'ms') {
      const opts = state.ans[id]?.options ?? [];
      if (opts.length) {
        decisions.push({ q: n.q || n.title, a: opts.map((o) => o.label).join(', '), multi: true });
        opts.forEach((o) => (o.tools ?? []).forEach((t) => toolSet.add(t)));
      }
    } else if (n.type === 'rec') {
      recBlocks.push({ title: n.title, tagline: n.tagline, pts: n.pts, tools: n.tools ?? [] });
    } else if (n.type === 'matrix') {
      n.rows.forEach((r) => (r.tools ?? []).forEach((t) => toolSet.add(t)));
    }
  }

  const tools = Array.from(toolSet);
  const terminal = tree[path[path.length - 1]] as TreeNode | undefined;

  // Sorted matrix rows (same ordering the matrix renderer uses).
  const matrixRows =
    terminal?.type === 'matrix'
      ? [...terminal.rows].sort((a, b) => (b.pubPotential + b.novelty) - (a.pubPotential + a.novelty))
      : null;

  // ── Markdown serialization for download ───────────────────
  function buildMarkdown(): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
    const L: string[] = [];
    L.push(`# ${moduleTitle} — Your Workflow`);
    L.push(`_Generated by the KAI Decision Engine · ${date}_`);
    L.push('');

    if (decisions.length) {
      L.push('## Your decisions');
      decisions.forEach((d, i) => {
        L.push(`${i + 1}. **${d.q}**`);
        L.push(`   - ${d.multi ? 'Selected: ' : ''}${d.a}`);
      });
      L.push('');
    }

    if (recBlocks.length) {
      L.push('## Recommended workflow');
      recBlocks.forEach((b) => {
        L.push(`### ${b.title}`);
        if (b.tagline) L.push(`_${b.tagline}_`);
        b.pts.forEach((p) => L.push(`- ${p}`));
        L.push('');
      });
    }

    if (matrixRows) {
      L.push('## Ranked recommendations');
      matrixRows.forEach((r, i) => {
        L.push(`${i + 1}. **${r.label}**${i === 0 ? ' _(top pick)_' : ''}`);
        if (r.tools?.length) L.push(`   - Tools: ${r.tools.join(', ')}`);
        L.push(`   - ${r.rationale}`);
      });
      L.push('');
    }

    if (terminal?.type === 'timeline') {
      L.push('## Timeline');
      terminal.phases.forEach((p) => {
        L.push(`### ${p.period}`);
        p.tasks.forEach((t) => L.push(`- ${t}`));
        L.push('');
      });
    }

    if (terminal?.type === 'checklist') {
      L.push('## Checklist');
      terminal.items.forEach((it) => L.push(`- [ ] ${it.label}${it.required ? ' (required)' : ''}`));
      L.push('');
    }

    if (tools.length) {
      L.push('## Tools & resources');
      tools.forEach((t) => L.push(`- ${t}`));
      L.push('');
    }

    L.push('---');
    L.push('Kai Genomics · kai-genomics.vercel.app');
    return L.join('\n');
  }

  const handleDownload = () => {
    downloadText(`kai-${moduleId}-workflow.md`, buildMarkdown());
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 2500);
  };

  return (
    <div className="workflow-summary">
      <CatTag label="WORKFLOW COMPLETE" />
      <h1 className="node-title">Your</h1>
      <h1 className="node-title italic" style={{ marginTop: -8, marginBottom: 24 }}>
        {moduleTitle.replace(/\s*(Decision Engine|Advisor|Assistant|Selector|Wizard|Checker|Recommender|Explorer|Planner|Tree|Selection)\s*$/i, '')} Workflow
      </h1>

      {chips.length > 0 && (
        <div className="sum-tags">
          {chips.map((c, i) => (
            <div key={i} className="sum-tag">
              <span className="tag-k">{c.k.toUpperCase()}&nbsp;&nbsp;</span>
              <span className="tag-v">{c.v}</span>
            </div>
          ))}
        </div>
      )}

      {/* Decision trail */}
      {decisions.length > 0 && (
        <>
          <SecLabel>Your Decisions</SecLabel>
          <div style={{ marginBottom: 32 }}>
            {decisions.map((d, i) => (
              <div key={i} className="wf-s">
                <div className="wf-n">{String(i + 1).padStart(2, '0')}</div>
                <div>
                  <div className="wf-d" style={{ marginBottom: 3 }}>{d.q}</div>
                  <div className="wf-l" style={{ color: 'var(--accent)' }}>
                    {d.multi ? '✓ ' : '→ '}{d.a}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </>
      )}

      {/* Recommended workflow from rec nodes */}
      {recBlocks.map((b, bi) => (
        <div key={bi} style={{ marginBottom: 28 }}>
          <SecLabel>{recBlocks.length > 1 ? `Recommendation ${bi + 1}` : 'Recommended Workflow'}</SecLabel>
          <div className="wf-l" style={{ fontSize: 14, marginBottom: 4 }}>{b.title}</div>
          {b.tagline && <p className="tagline" style={{ marginBottom: 16 }}>{b.tagline}</p>}
          <div className="pts">
            {b.pts.map((p, i) => (
              <div key={i} className="pt">
                <div className="pt-arr">→</div>
                <div className="pt-txt">{p}</div>
              </div>
            ))}
          </div>
        </div>
      ))}

      {/* Ranked matrix result */}
      {matrixRows && (
        <div style={{ marginBottom: 28 }}>
          <SecLabel>Ranked Recommendations</SecLabel>
          {matrixRows.map((r, i) => (
            <div key={i} className="wf-s" style={i === 0 ? { borderLeft: '2px solid var(--accent)', paddingLeft: 12 } : undefined}>
              <div className="wf-n">{String(i + 1).padStart(2, '0')}</div>
              <div>
                <div className="wf-l">
                  {i === 0 && <span style={{ color: 'var(--accent)', fontSize: 9, letterSpacing: '1.5px', marginRight: 8 }}>TOP PICK</span>}
                  {r.label}
                </div>
                {r.tools && r.tools.length > 0 && (
                  <div className="wf-d" style={{ color: 'var(--accent2)' }}>{r.tools.join(' · ')}</div>
                )}
                <div className="wf-d">{r.rationale}</div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Timeline result */}
      {terminal?.type === 'timeline' && (
        <div style={{ marginBottom: 28 }}>
          <SecLabel>Your Timeline</SecLabel>
          {terminal.phases.map((p, i) => (
            <div key={i} style={{ marginBottom: 16 }}>
              <div className="wf-l" style={{ color: 'var(--accent)', marginBottom: 6 }}>{p.period}</div>
              {p.tasks.map((t, j) => (
                <div key={j} className="cl-i" style={{ borderBottom: 'none', padding: '4px 0' }}>
                  <div className="cl-b" />
                  <div className="cl-t">{t}</div>
                </div>
              ))}
            </div>
          ))}
        </div>
      )}

      {/* Checklist result */}
      {terminal?.type === 'checklist' && (
        <div style={{ marginBottom: 28 }}>
          <SecLabel>Your Checklist</SecLabel>
          {terminal.items.map((it) => (
            <div key={it.id} className="cl-i">
              <div className="cl-b" />
              <div className="cl-t">
                {it.label}
                {it.required && <span style={{ color: 'var(--accent2)', fontSize: 9, marginLeft: 8 }}>REQUIRED</span>}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Tools */}
      {tools.length > 0 && (
        <>
          <SecLabel>Tools &amp; Resources</SecLabel>
          <div className="pills">
            {tools.map((t) => <span key={t} className="pill">{t}</span>)}
          </div>
        </>
      )}

      {/* Actions */}
      <div className="ws-actions">
        <button className="btn-p" onClick={() => window.print()}>⎙ Print workflow</button>
        <button className="btn-p" onClick={handleDownload}>
          {downloaded ? '✓ Downloaded' : '↓ Download (.md)'}
        </button>
      </div>
      <div className="ws-actions ws-actions--ghost">
        <button className="btn-ghost" onClick={onRestart}>↺ Start over</button>
        <button className="btn-ghost" onClick={onHub}>← All modules</button>
      </div>
    </div>
  );
}
